add property
SirRender00/texasholdem pull request #194
Opened 2023-05-24 06:00 UTC by LucasColas

Hello,
I added a property for the attribute called action. I think it's useful.
Because sometimes you can need to have access to the last action. self._action is supposed to be encapsulated.

2023-05-24 15:59 UTC, SirRender00 requested changes
Sounds reasonable 👍. You'll need to add a docstring on the function AND at the top of the class, you can add it to the `attributes` for the docstring of the class.

2023-05-24 15:59 UTC, SirRender00 commented on texasholdem/game/game.py
> +    def action(self) -> tuple:
```suggestion
    def action(self) -> Tuple[ActionType, Optional[int]]:

```

2023-05-28 08:13 UTC, LucasColas commented
> Sounds reasonable 👍. You'll need to add a docstring on the function AND at the top of the class, you can add it to the `attributes` for the docstring of the class.

Done.

2023-05-30 16:00 UTC, SirRender00 commented on texasholdem/game/game.py
> +
```suggestion


```

2023-05-31 04:12 UTC, SirRender00 commented
@LucasColas Also feel free to run pylint locally with `poetry run pylint texasholdem/`

2023-06-07 05:12 UTC, SirRender00 commented
@LucasColas Looks like you have to run `poetry run black .` to format the code.

2023-06-18 19:30 UTC, LucasColas commented
I'll do it.

2023-06-30 15:49 UTC, LucasColas commented
To be honest, I don't really understand how to install poetry.

2023-06-30 16:07 UTC, LucasColas commented
Ok, I think I understood. I did a new commit.

2023-07-04 04:21 UTC, LucasColas commented
How to handle codecov ?

2023-07-04 06:46 UTC, SirRender00 approved these changes

2023-07-04 06:47 UTC, SirRender00 commented
Ah yeah don't worry about codecov, I'll merge this in 👍

2023-07-04 06:47 UTC, merged